version: '3.7'

services:

  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc2
    ports:
      - 3307:3306
    networks:
      - easyhome-net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  easy-home-app:
    platform: linux/x86_64
    build: ./Application
    environment:
      server: "mysql"
      port: "3307"
      database: "tcc2"
      username: "root"
      password: "root"
      SendGridKey: "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"
      Key: "E546C8DF278CD5931069B522E695D4F2"
    
    networks:
      - easyhome-net

    depends_on:
      mysql:
        condition: service_healthy


networks:
  easyhome-net:
    driver: bridge