version: '3.7'
services:

  easyhome-app:
    build: .
    ports: 
     - "8000:80"
     - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
      - SERVER=${SERVER}
      - PORT=${PORT}
      - DATABASE=${DATABASE}
      - USERNAME=root
      - PASSWORD=${PASSWORD}
      - Key=${Key}
      - SendGridKey=${SendGridKey}
 
    volumes:
      - ./conf.d/https/:/https/


    networks:
      - easyhome-net

  
networks:
  easyhome-net:
    driver: bridge