version: '3.7'
services:

  easyhome-app:
    build: .
    ports: 
     - "8000:80"
    environment:
      - SERVER=${SERVER}
      - PORT=${PORT}
      - DATABASE=${DATABASE}
      - USERNAME=root
      - PASSWORD=${PASSWORD}
      - Key=${Key}
      - SendGridKey=${SendGridKey}
 
    volumes:
      - ./conf.d/https/:/https/


    networks:
      - easyhome-net

  
networks:
  easyhome-net:
    driver: bridge